### ISSUE TITLE
Упрощение dynamicscene.xml для r1m2 (Риджин)

### ISSUE THREAD

**Issue by lineisover** [DeusExMachinaTeam/EM-CommunityPatch#103]
#8 - общая таска по упрощению динамиксцен.
Упрощения динамиксцены для Риджина. Точно можно порезать деревья, по объектам надо очень точно определиться что режем, что нет.

**Comment by DeusExMachinaTeam** [comment]
Согласно текущим данным в изменении нет необходимости, вылеты вызваны другим
