### ISSUE TITLE
Упрощение dynamicscene.xml для r2m1 (Либриум)

### ISSUE THREAD

**Issue by lineisover** [DeusExMachinaTeam/EM-CommunityPatch#104]
#8 - общая таска по упрощению динамиксцен.
Упрощения динамиксцены для Либриума. Точно можно порезать деревья, по объектам надо очень точно определиться что режем, что нет.

**Comment by DeusExMachinaTeam** [comment]
Согласно текущим данным в изменении нет необходимости, вылеты вызваны другим
