### ISSUE TITLE
LastId в Dynamicscene.xml карты, ломает сейвы

### ISSUE THREAD

**Issue by Avallagni** [DeusExMachinaTeam/EM-CommunityPatch#182]
>Семимахов: Ещё про вылеты.
Для модеров нормально править xml-файлы вручную. Но конкретно с dynamicscene.xml могут быть проблемы, если значение LastId неверно.
Тут столкнулся с интересной проблемой в меридиане. Игра стартует нормально и весь уровень проходится без вылетов. По ходу делал сохранки, и с некоторой сохранки игра перестала грузится, как и с последующих. А с предыдущих грузилась.
Оказалось дело в некорректном значении LastId. Если значение LastId меньше, чем нужно, то при переходе на новую карту не все объекты загружаются. Естественно, это может приводить к вылетам. Видимо, и в сохранку не все попадают.
В общем, поправил LastId, и всё стало сохраняться нормально. Такшта, надо следить за LastId.

**Comment by DeusExMachinaTeam** [comment]
не удалось отследить где оно ломается и влияет ли реально на поломку сейвов
