### ISSUE TITLE
Человечки останавливаются в миллиметре от машины и дохнут

### ISSUE THREAD

**Issue by zatinu322** [DeusExMachinaTeam/EM-CommunityPatch#188]
Надо разобраться окда?

**Comment by DeusExMachinaTeam** [comment]
Разобрались, поправить относительно малой кровью не получится. Человечки останавливаются в момент столкновения с колизией машины. Нет прямолинейного варианта как можно заставить их останавливаться раньше, так как фактически физ движок является источником ивента для остановки. Тесты по снижению порога скорости столкновения с человечком который считается равным его смерти не дали хорошего результата, поскольку если увеличить его достаточно для того чтобы от человечка было легко отъехать, появляется так же возможность медленно проежать сквозь человечков, будто это призраки.
WNI.
