### ISSUE TITLE
Звуковые эффекты некорректно отнесены к "Громкость голоса"

### ISSUE THREAD

**Issue by DeusExMachinaTeam** [DeusExMachinaTeam/EM-CommunityPatch#192]
Многие звуковые эффекты некорректно отнесены и управляются ползунком "Громкости голоса"
Как пример - перезарядка и звуки меню

**Comment by lineisover** [comment]
Перезарядку я же фиксил

**Comment by DeusExMachinaTeam** [comment]
Перезарядка исправлена в #444. Проблема заключается в том что сами ползунки имеют обманчивую подпись, на деле Громкость голоса это "2D звуки", а Громкость эффектов - "3D звуки". Звуки меню это 2D эффект, переносить его в "Громкость эффектов" неочевидное решение, плюс категория звуков интерфейса это хардкод движка. Пока закрываем как частично Done/ частично WNI.
