### ISSUE TITLE
Скриптовые правки 2.0

### ISSUE THREAD

**Issue by zatinu322** [DeusExMachinaTeam/EM-CommunityPatch#253]
Создал второй том, а то в первом уже сложно ориентироваться.

**Общее**

- [x] Поставить инфекшн-Уралам в Хеле возможность дропать нефть и горючее. [Пока не надо, ибо непонятно что там с инфекшеном в целом]
- [x] Уралы в Роще не дропают бутылки с табаком [Пока не надо, ибо непонятно что там с инфекшеном в целом]
- [x] Уралы в Аржане не дропают ничего кроме говнооружия [Пока не надо, ибо непонятно что там с инфекшеном в целом]
- [ ] Провалить все квесты, какие можно, и прибраться, если будет что.
- [x] Поставить метку на OldTownOutsiderCar TEAM, а не имя.
- [ ] Овер знает, как поправить эффекты привязанные на громкость речи.

**Край**

- [x] Скорость скролла титров в самом начале (оставим на потом, там нюансы HD/не HD)

**Риджин**

- [x] Ролик въезда/выезда в Порто (ждём, пока перемоделят Порто)

**Фатерлянд**

- [ ] trStartMap вызывает ошибку в логе QuestName doesn't exist. Непонятно как оно работает и работает ли.

**Хель**
- [x] При отказе от переезда Хель - Фентельярд и сохранение сразу после, если загрузить - не можем управлять машиной.

**Роща Друидов**
- [x] Одинокому Друиду сделать диолог, чтобы можно было мериться ~~писюнами~~ с СО, но не в том случае, если ты их убил.

**Аржан**
- [x] В катсцене с поимкой Лисы возле монастыря, ГГ и Лиса стоят **в** дороге

**Вахат**
- [x] Во время участия в гонках старая машина ГГ долбится в стены из-за вейпоинта ненужного.

**Comment by DeusExMachinaTeam** [comment]
@zatinu322 закрываем? Те несколько пунктов что остались звучат довольно непонятно.
