### ISSUE TITLE
Переработка гаджетов, разделение и более понятное описание гаджетов 

### ISSUE THREAD

**Issue by Zvetkov** [DeusExMachinaTeam/EM-CommunityPatch#28]
Пушки улучшаются гаджетами для огнестрельного оружия, а должны для артиллерии

**Comment by DeusExMachinaTeam** [comment]
Не планируется исправлять в комреме из-за необходимости ребаланса видов оружия и самих гаджетов для того чтобы переработка числа и типов гаджетов имела смысл. Так же создаёт вопросы о том насколько ванила-френдли будет переделать все гаджеты и поменять эффект привычных конфигураций гаджетов.
