### ISSUE TITLE
Проблемы с фильтрацией текстур в новых шейдерах КомРема

### ISSUE THREAD

**Issue by DeusExMachinaTeam** [DeusExMachinaTeam/EM-CommunityPatch#394]
Мыло при отклонении от 90 градусов. Отлично заметно при начале новой игры и медленном кручении камеры вокруг Вена, смотря на логотип Farmer на кузове
В чистой игре во всех положениях логотип в фокусе. В комреме два варианта мыла при повороте, сперва где-то под угол в 30 градусов от нормали, мылится существенно, потому полное шакалити при отклонении от нормали градусов на 60
Сравнение:
![unknown2](https://user-images.githubusercontent.com/79088546/160234418-da538d62-948b-42c5-93cf-7a5c4a62feb2.png)
![unknown](https://user-images.githubusercontent.com/79088546/160234422-58f8b8f8-5bfc-43be-bf23-fea058d5fe08.png)

**Comment by ThePlain** [comment]
Fixed
