### ISSUE TITLE
Красивый Readme.md

### ISSUE THREAD

**Issue by DeusExMachinaTeam** [DeusExMachinaTeam/EM-CommunityPatch#409]

**Comment by DeusExMachinaTeam** [comment]
![comremaster_just_text_shadow](https://user-images.githubusercontent.com/79088546/174285285-ce88816e-fd98-46a6-ba50-f579ed2b8583.PNG)

**Comment by DeusExMachinaTeam** [comment]
![comremaster_just_text_shadow](https://user-images.githubusercontent.com/79088546/174285554-cf467b80-7264-475f-94ec-bacc204b04c9.png)

**Comment by DeusExMachinaTeam** [comment]
![screen00148](https://user-images.githubusercontent.com/79088546/174292723-5bf3f34b-4c75-4246-a24d-324d3b35d671.jpg)

**Comment by DeusExMachinaTeam** [comment]
![screen00149](https://user-images.githubusercontent.com/79088546/174292736-f51558e0-1a1e-4c9e-90e8-a707a1fb1ee7.jpg)

**Comment by DeusExMachinaTeam** [comment]
![screen00147](https://user-images.githubusercontent.com/79088546/174293216-03fa560d-1204-4c7a-b947-65c4b59c1d46.jpg)

**Comment by DeusExMachinaTeam** [comment]
![screen00074](https://user-images.githubusercontent.com/79088546/174293239-7f7a3fda-edc9-4bb2-bcfb-dba1b6f46838.jpg)

**Comment by DeusExMachinaTeam** [comment]
![screen00152](https://user-images.githubusercontent.com/79088546/174297723-d91c61c2-c240-4733-b195-88d84ad6c709.jpg)

**Comment by DeusExMachinaTeam** [comment]
![screen00155](https://user-images.githubusercontent.com/79088546/174297984-78026b06-8d27-4ee4-aa71-25292a443d07.jpg)

**Comment by DeusExMachinaTeam** [comment]
![Discord-Logo-Color](https://user-images.githubusercontent.com/79088546/174304599-33630ab1-e5ce-4410-a720-55046783d085.png)

**Comment by DeusExMachinaTeam** [comment]
![Discord-Logo-sml](https://user-images.githubusercontent.com/79088546/174305431-1ac462ce-beeb-425c-a7d0-b39f07c08991.png)

**Comment by DeusExMachinaTeam** [comment]
![Discord-Logo-sml](https://user-images.githubusercontent.com/79088546/174305727-755adfa0-57c2-41b0-9717-8476fcbc4567.png)

**Comment by DeusExMachinaTeam** [comment]
![YouTube_logo_sml](https://user-images.githubusercontent.com/79088546/174310152-da71224b-5c5f-4448-be42-31d0bc703360.png)

**Comment by DeusExMachinaTeam** [comment]
![logo_trasparent_sml](https://user-images.githubusercontent.com/79088546/174311991-c20e04bb-1cad-44e2-a0e9-5984de6d8d55.png)

**Comment by DeusExMachinaTeam** [comment]
![2022-06-17 17_00_37-Slack _ ! Denis Kutsenko _ NVIDIA Corporation _ 2 new items](https://user-images.githubusercontent.com/79088546/174313893-ed72e5a4-4fff-4617-9610-e879f457c12d.png)

**Comment by DeusExMachinaTeam** [comment]
![em2ch](https://user-images.githubusercontent.com/79088546/174318046-57660bc9-010b-40d8-870d-0623b3fe57e2.png)

**Comment by DeusExMachinaTeam** [comment]
![square_big](https://user-images.githubusercontent.com/79088546/174318503-df5a0f09-86b2-4f0f-984f-cc41f2d1990e.png)

**Comment by DeusExMachinaTeam** [comment]
![pavlik_logo](https://user-images.githubusercontent.com/79088546/174320128-a8550d1c-2960-4aa1-8de6-8e414b2a8469.png)

**Comment by DeusExMachinaTeam** [comment]
![use_releases](https://user-images.githubusercontent.com/79088546/174327479-67ac216d-d01a-4d0d-958b-aca2a141c5e4.png)

**Comment by DeusExMachinaTeam** [comment]
merged in #410

**Comment by DeusExMachinaTeam** [comment]
![commod_screen](https://user-images.githubusercontent.com/79088546/210018626-be1889a5-54bb-4abf-9736-debef2981cbd.png)

**Comment by DeusExMachinaTeam** [comment]
![commod_screen](https://user-images.githubusercontent.com/79088546/210018652-8d3dd172-d151-4b95-afa1-4282eff38305.png)

**Comment by Zvetkov** [comment]
![forum_link](https://github.com/user-attachments/assets/bff2db8d-337a-4d3c-8d90-b95e29a61486)

**Comment by DeusExMachinaTeam** [comment]
![forum_link](https://github.com/user-attachments/assets/31c80482-7a40-4592-81ee-108800222bdf)

**Comment by DeusExMachinaTeam** [comment]
![forum_link](https://github.com/user-attachments/assets/8cc56782-08ce-4955-8db8-796e9bdb613e)

**Comment by DeusExMachinaTeam** [comment]
![forum_link](https://github.com/user-attachments/assets/e4ab98f4-93de-40a9-a65a-485e4a2e9e95)
