### ISSUE TITLE
Отсутствует текстура Мидгарда

### ISSUE THREAD

**Issue by megoRU** [DeusExMachinaTeam/EM-CommunityPatch#411]
Не знаю как тут принято репортить у вас но:
1. [Сейвы](https://disk.yandex.ru/d/kibckQDgXXCMhg)
2. [Папка data](https://disk.yandex.ru/d/p76mMivED_-LjQ)

P. S. Save load не помогло. И перезапуск игры

UPD: Странно после второго раза запуска игры он появился, но на скриншоте загрузки его нет)

![image](https://user-images.githubusercontent.com/23276305/174328770-2a2f1e8f-c6a4-414d-ad3c-8ae765305f77.png)

**Comment by ThePlain** [comment]
Поведение перед вылетом. Проблема DXRender9.dll #412
