### ISSUE TITLE
Вылет на игнотт

### ISSUE THREAD

**Issue by megoRU** [DeusExMachinaTeam/EM-CommunityPatch#414]
Ехал от оракула к выезду с карты

[exceptions.zip](https://github.com/DeusExMachinaTeam/EM-CommunityPatch/files/8934158/exceptions.zip)

**Comment by Gnome627** [comment]
Окей, ловил в этом же месте, когда тестировали разные варианты.
Хотелось бы узнать спеки компа и в каком состоянии была система в момент вылета, то есть были ли открыты какие-то сторонние программы и как долго компьютер был включён.

**Comment by megoRU** [comment]
1. Chrome 1-2 вкладки ютуб, afterburner + rivatuner
2. i7 4790k 4.6 ггц, 16 гб рам, gtx 1070
3. Часов 8 пк был включен +-

**Comment by ThePlain** [comment]
Это StackOverflow. К сожалению не удалось словить место вызова что бы определить причину.
