### ISSUE TITLE
Растянутые иконки группировок в энциклопедии

### ISSUE THREAD

**Issue by Maxis2012** [DeusExMachinaTeam/EM-CommunityPatch#415]
В окне просмотра записей в энциклопедии иконки группировок растянуты горизонтально.
![logo2](https://user-images.githubusercontent.com/52010865/178667943-f1ad9161-9c26-41d0-bf4d-f8320e3f8a54.png)

**Comment by DeusExMachinaTeam** [comment]
К сожалению в предложенном виде WNI, мне не нравится получающийся баланс между размером моделей авто и логотипами. Скорректировал размер поля ближе к предложенному чтобы логотипы были растянуты меньше
