### ISSUE TITLE
Некорректная работа patcher.exe во время установки модификаций

### ISSUE THREAD

**Issue by zatinu322** [DeusExMachinaTeam/EM-CommunityPatch#424]
1. Если отказаться от установки модификации (ввести "no"), то этот ответ всё равно будет интерпретирован как "yes" и установка продолжится. Такое происходит, когда в папке mods находится только один мод. С двумя и более не проверял.
2. Некорректно работает проверка установленного дополнительного контента ремастера, который указывается в prerequisites в манифесте мода. Даже если допконтент не установлен (в data/mod_manifest для него указано "skip"), то он всё равно валидируется как установленный, и после этого стартует установка мода, чего быть не должно.
3. Лог лучше писать в utf-8, а не в cp1251. Приняли это решение на основе нашего диалога в лс от 09/12/22

Лог установки и манифест от isl прикладываю. Алгоритм действий был следующий:
options --> remaster --> options --> no --> no --> no --> Enter --> yes --> no(!!!) --> Enter --> Enter

no(!!!) = отказ от установки мода. Тем не менее, установка продолжилась.
В папке модс находилась только папка ImprovedStoryline106 с манифестом внутри.

[debug_2022-10-15_16-23-46.log](https://github.com/DeusExMachinaTeam/EM-CommunityPatch/files/9792165/debug_2022-10-15_16-23-46.log)
[manifest.txt](https://github.com/DeusExMachinaTeam/EM-CommunityPatch/files/9792168/manifest.txt)

Изменил расширение манифеста на txt, так как yaml гит не грузил. Исходное его расширение было yaml.

**Comment by lineisover** [comment]
Павлик иди работать тестировщиком, это твоё

(простите)

**Comment by zatinu322** [comment]
Дополнение к п.1
Если в папке mods более одного мода, то всё равно устанавливается самый первый из предложенных, независимо от ответа "yes" или "no".

**Comment by DeusExMachinaTeam** [comment]
Should be resolved in #432
