### ISSUE TITLE
English localization v1 (text only)

### ISSUE THREAD

**Issue by zatinu322** [DeusExMachinaTeam/EM-CommunityPatch#438]
data/if/dialogs_16_9/

- [x] credits.xml

data/if/dialogs/

- [x] credits.xml (not sure we need it)

data/if/diz/

- [x] dialogsglobal.xml
- [x] dynamicdialogsglobal.xml
- [x] levelinfo.xml (not sure we need it)
- [x] levelinfo_hd.xml
- [x] model_names.xml
- [x] questinfoglobal.xml

data/if/strings/

- [x] affixesdiz
- [x] bindnames
- [x] clansdiz
- [x] fadingmsgs
- [x] gamestrings
- [x] help
- [x] msgpatterns.xml (not sure we need it)
- [x] objectdiz
- [x] setupstrings (not sure we need it as well)
- [x] statistics
- [x] uibooks
- [x] uidescription
- [x] uieditstrings
- [x] uihistory

data/maps/r1m1/

- [x] object_names.xml
- [x] strings.xml

data/maps/r1m2/

- [x] object_names.xml
- [x] strings.xml

data/maps/r1m3/

- [x] object_names.xml
- [x] strings.xml

data/maps/r1m4/

- [x] object_names.xml
- [x] strings.xml

data/maps/r2m1/

- [x] object_names.xml
- [x] strings.xml

data/maps/r2m2/

- [x] object_names.xml
- [x] strings.xml

data/maps/r3m1/

- [x] object_names.xml
- [x] strings.xml

data/maps/r3m2/

- [x] object_names.xml
- [x] strings.xml

data/maps/r4m1/

- [x] object_names.xml
- [x] strings.xml

data/maps/r4m2/

- [x] object_names.xml
- [x] strings.xml

data/sounds/radio/

- [x] radiosamples.xml

**Comment by DeusExMachinaTeam** [comment]
Fully integrated starting with 1.14.1 release.
