### ISSUE TITLE
Remove trash from questinfoglobal.xml

### ISSUE THREAD

**Issue by zatinu322** [DeusExMachinaTeam/EM-CommunityPatch#439]
['d_Glagiators_Quest', 
'd_MerIsThief_Quest', 
'd_ReturnToBen_Quest', 
'd_ReturnTuzzAfterTunel_Quest', 
'd_TalkAboutAksel_Quest', 
'd_TalkAboutLisa_Quest', 
'r1m3_FindManyWorkers_Quest', 
'r2m2_FightWithAxelInArena_Quest1', 
'r2m2_FindMrPresident', 
'r2m2_ReturnToMarecciaFromMrPresident']

**Comment by zatinu322** [comment]
@Zvetkov закрывать будешь? Помёржено же

**Comment by DeusExMachinaTeam** [comment]
Done in #443
