### ISSUE TITLE
Ремастер звуков или замена нескольких звуков как дополнение к ремастеру

### ISSUE THREAD

**Issue by Destya0419** [DeusExMachinaTeam/EM-CommunityPatch#455]
Условный звук КПВТ из Аркады перенести в ремастер, ну мб ещё парочку звуков прикольных

**Comment by DeusExMachinaTeam** [comment]
В данный момент такая опция для КомРема не планируется, но могу предложить вам сделать это в виде отдельного мода или добавить в какой-то большой мод.
