### ISSUE TITLE
Awful font in ComPatch console

### ISSUE THREAD

**Issue by zatinu322** [DeusExMachinaTeam/EM-CommunityPatch#460]
Fix pls

**Comment by DeusExMachinaTeam** [comment]
Предлагаю всё же не имплементировать. 
КомПатч презентуется в первую очередь как опция совместимости для 4:3 экранов, соответственно предполагается что установливать и тестировать моды совместимые с ним нужно не на 16:9.
Правка консоли под 16:9 сделает её хуже на 4:3, поэтому кажется что всё же нет смысла её менять.
