### ISSUE TITLE
Изменение названия игры и версии в exe через манифест мода

### ISSUE THREAD

**Issue by zatinu322** [DeusExMachinaTeam/EM-CommunityPatch#466]
Реквестирую фичу, чтобы в манифесте мода можно было бы написать строку, которую патчер потом применит в exe-шник и заменит обычную `Ex Machina Community Remaster v1.13 release build...`

Не то, чтобы прям жизненно необходимо, но было бы очень круто такое иметь.

@Zvetkov можна?

**Comment by DeusExMachinaTeam** [comment]
Это конфликтное изменение, хотелось бы не лезть туда с модами которых может быть любое количество и каждый хочет вписать что-то своё. Лучше было бы реализовать через кракен логирование всех установленных модов в консоль и отображение их списка в одном из игровых меню - либо в главном меню текстом либо в настройках есть свободное место.
