### ISSUE TITLE
Использование на Linux

### ISSUE THREAD

**Issue by Zalexanninev15** [DeusExMachinaTeam/EM-CommunityPatch#477]
Здравствуйте. Хотел бы использовать модификацию Community Remaster на установленной игре на дистрибутиве Linux. Всё распаковал, запускаю `commod.exe`, через несколько секунд он стартует и вылетает. Пробовал запускать из префикса игры через Protontricks и через PortProton - результат один и тот же. Через Wine запускается, но... пользоваться невозможно. 
![image](https://github.com/DeusExMachinaTeam/EM-CommunityPatch/assets/51060911/8d02ebda-bfda-48f7-b526-b832541570b8)
Можно ли установить модификацию без лаунчера?

**Comment by DeusExMachinaTeam** [comment]
Linux юзер в дискорде у которого работает лаунчер подсказал что необходимо отлючить dxvk для процесса лаунчера в Wine:
> Я просто выключил dxvk через перемнную среды, но у меня на префиксе wine установлена куча библиотек, в том числе дотнеты
> WINEDLLOVERRIDES="*d3d9,*d3d10,*d3d10_1,*d3d10core,*d3d11,*dxgi=b" wine commod-2.0.9.exe

Были и другие юзеры у которых работает лаунчер в unix среде под эмуляцией. Официальной поддержки Linux на данный момент нет, установить без лаунчера мод не получится, лаунчер вносит бинарные правки в exe и dll игры.
