### ISSUE TITLE
Патчер из релиза 1.14 не патчит игру, при этом патчер из 1.13 отрабатывает

### ISSUE THREAD

**Issue by mvitaly2003** [DeusExMachinaTeam/EM-CommunityPatch#484]
Запускаю commod.exe, ввожу путь к игре, жму кнопку добавления, появляется восклицательный знак и слово "Ошибка", пробовал разные дистрибутивы, эффект один. Попробовал предыдущий релиз 1.13, где консольный патчер - всё отработало успешно.

В журнале активности из Process Monitor видно, что процесс обращается к экзешнику, дллкам, пачке ресурсов из папки data, к config.cfg, и конец. Может, что-то в config.cfg не понравилось? Хорошо бы какие-то подробности видеть, что именно не понравилось, если папка игры не устраивает.

**Comment by IhorBorovskyi** [comment]
привет, в релизе по ссылке: https://github.com/DeusExMachinaTeam/EM-CommunityPatch/releases/tag/v1.14-230616a
скачай файл commod-2.0.9.exe что отдельным файлом там лежит, и пробуй через него.

**Comment by mvitaly2003** [comment]
О, этому мой дистрибутив нравится, спасибо! Думал, это тот же, что и в архиве. Но не пойму, он теперь не патчит игру, а подсовывает ей изменения виртуально? Не нашёл кнопки патча.
