### ISSUE TITLE
Vehicle stuck turning right and loader boss fight moving away

### ISSUE THREAD

**Issue by Tapeworm12** [DeusExMachinaTeam/EM-CommunityPatch#513]
This was caused when I load the game, the vehicle is stuck turning right but it's fine when I change to left. But when I release the arrow keys it somehow turns wheels right. This makes so hard to control the vehicle, especially while on Belaz.

When the boss fight with the loader starts, the crane moves away only to display an error. 
![20240731144501_1](https://github.com/user-attachments/assets/32a694af-1f6c-4ffb-b12d-92da23e4d4c8)
![20240731144737_1](https://github.com/user-attachments/assets/343d2cb7-258e-45e1-a87b-8de443a125bb)

I'm using the Steam version

**Comment by Zvetkov** [comment]
Please unplug your gamepad or similar controller from the PC, it interferes with the game inputs.
