### ISSUE TITLE
Тени от солнца на моделях

### ISSUE THREAD

**Issue by Zvetkov** [DeusExMachinaTeam/EM-CommunityPatch#52]
R&D по теме: "кстати в теории тени от солнца можно и в оригинале сделать"

- [x] Force Shader Model 3.0
- [ ] Fix passing shader registers
- [ ] Добавление тени от ландшафта
- [ ] Включение теней от всех объектов

Исправление шейдеров:
- [ ] alphasampler.fx
- [ ] blurshadow.fx
- [x] bump.fx
- [x] bumpdiffuse_envalphagloss_nospec.fx
- [x] bumpdiffuse_envalphagloss_spec.fx
- [x] bump_vc.fx
- [ ] contour.fx
- [ ] decals.ps
- [ ] decals.vs
- [x] diffuse.fx
- [x] diffuse_detail.fx
- [x] diffuse_detail_vc.fx
- [ ] diffuse_emmision.fx
- [ ] diffuse_shells.fx
- [x] diffuse_vc.fx
- [ ] grassshadows.ps
- [ ] grassshadows.vs
- [ ] grasstest_ps11.ps
- [ ] grasstest_vs11.vs
- [ ] impostortest_ps11.ps
- [ ] impostortest_vs11.vs
- [ ] landscapedeep_ps20.ps
- [ ] landscapedeep_ps20.vs
- [ ] landscapefp_ps11.ps
- [ ] landscapesolidbind_ps11.ps
- [ ] landscapesolidbind_ps11.vs
- [ ] landscapesolid_ps11.ps
- [ ] landscapesolid_ps11.vs
- [ ] landscapesp_ps11.ps
- [ ] landscape_ps11.vs
- [ ] lib.fx
- [ ] libsamplers.fx
- [ ] lightmap_detail.fx
- [ ] lsdetailedshadows.fx
- [ ] lslight.fx
- [ ] lsprojector.fx
- [ ] lsshadows.fx
- [ ] ls_cliff_color.fx
- [ ] ls_color.fx
- [ ] ls_color_alpha.fx
- [ ] ls_drawshadows.fx
- [ ] norm_cubemap.fx
- [ ] objectlight.fx
- [ ] objectprojector.fx
- [ ] post_blur_ps11.ps
- [ ] post_blur_ps20.ps
- [ ] post_blur_vs11.vs
- [ ] post_blur_vs20.vs
- [ ] post_bw_ps11.asm
- [ ] post_bw_ps11.vs
- [ ] post_composite_ps11.asm
- [ ] post_composite_ps20.asm
- [ ] post_composite_vs11.vs
- [ ] post_composite_vs20.vs
- [ ] post_downsample_ps11.ps
- [ ] post_downsample_ps20.ps
- [ ] post_downsample_vs11.vs
- [ ] post_downsample_vs20.vs
- [ ] post_film_ps11.asm
- [ ] post_film_ps11sp.asm
- [ ] post_film_vs11.vs
- [ ] ps_dust.fx
- [ ] ps_light.fx
- [ ] ps_nofog_dust.fx
- [ ] ps_nofog_light.fx
- [ ] road.fx
- [ ] roaddetailedshadows.fx
- [ ] roadlight.fx
- [ ] roadprojector.fx
- [ ] roadshadows.fx
- [ ] roadsprite.fx
- [ ] road_detail.fx
- [ ] rope.fx
- [ ] rtsampler.fx
- [ ] scatterlib.fx
- [ ] shadow.fx
- [ ] skybox.fx
- [x] specular.fx
- [ ] specular_cubemap.fx
- [x] specular_vc.fx
- [ ] surf.fx
- [ ] tree.fx
- [ ] treelight.fx
- [ ] treeprojector.fx
- [ ] tree_detail_vc_nolights.fx
- [ ] tree_nolights.fx
- [ ] tree_vc_nolights.fx
- [ ] watertestlow_ps20.ps
- [ ] watertestlow_ps20.vs
- [ ] watertestmed_ps20.ps
- [ ] watertestmed_ps20.vs
- [ ] watertest_ps11.asm
- [ ] watertest_ps11.vs
- [ ] watertest_ps14.asm
- [ ] watertest_ps14.vs
- [ ] watertest_ps20.ps
- [ ] watertest_ps20.vs
- [ ] water_dumb.ps
- [ ] water_dumb.vs
- [ ] wheeltrace.fx

**Comment by ThePlain** [comment]
В текущий момент не реализуемо, требуется реверс и исправление в exe.
