### ISSUE TITLE
Инструмент для настройки моделей

### ISSUE THREAD

**Issue by DeusExMachinaTeam** [DeusExMachinaTeam/EM-CommunityPatch#53]
Текстуры/шейдеры/bonebounds/скины настраивать без блендера и без gsmed, для работы с gam в первую очередь.

**Comment by ThePlain** [comment]
Юзаем Blender + HTA Toolchain для любых моделей кроме персонажей.
Большую часть кейсов покрывается обычным реэкспортом.
