### ISSUE TITLE
Некорректное проигрывание анимации при последнем выстреле у пушек

### ISSUE THREAD

**Issue by ICAS-14** [DeusExMachinaTeam/EM-CommunityPatch#61]
Когда у пушки количество зарядов в "магазине" равняется 1, то при выстреле (т.е. количество зарядов в "магазине" становится равным 0) анимация MOVE1 проигрывается не полностью, а на пару кадров, что, зачастую, незаметно. По этой причине все однозарядные пушки (таковыми являются, например все плазменные пушки, все дробовики) как-будто бы не анимированы, хотя по-факту анимация имеется.

**Comment by DeusExMachinaTeam** [comment]
Исправлено где возможно
